### ISSUE TITLE
Boot to black screen after installation

### ISSUE THREAD

**Issue by nojohnso** [mighildotcom/X230-Hackintosh#2]
I was able to get all the way to the end of the installation. Copied over the EFI, checked sound, video playback, etc. After restart I just boot to a black screen. Any ideas on what I did wrong?

**Comment by verfasor** [comment]
Which means it’s just fine and maybe the EFI partition within the system is f’d up 

Try booting from USB installer once more. Check whether you can boot from that USB and enter the Catalina system. Test it first. 

What’s your X230’s specs btw? Unplug other usb volumes, external display and/or usb devices while booting. Also, what version of Catalina are you running?

I can’t say anything much without seeing your verbose log. Are you familiar with entering boot flags? Use “-v“ while booting, 

Refer to https://www.hackintosh.computer/2187/hackintosh-boot-flags/

**Comment by nojohnso** [comment]
System Specs:
- Catalina 10.5 
- Core i5-3320M
- 16GB Memory
- HD4000 Graphics
- 256GB SSD

Not sure if there's anything else you need from that.

My options are Clover are:
- Boot macOS Install from Install macOS Catalina
- Boot FileVault Prebooter from Preboot (_Is this normal or should there be a standard boot to Catalina as well?_)
- Boot Recovery from Recovery

I added the '-v' boot parameter and receive the following error: 
**** ERROR: _LoginUIInitializeGraphics Can't install updated AppleEvent protocol.
**** ERROR: FDELoginUIInitializeUsers _LoginUIInitializeGraphics failed err: 1

**Comment by verfasor** [comment]
Clover should have another option to finish the installation.

OR 

"Boot macOS Catalina from macOS-SSD-Name" if the installation went successful. 

FileVault Prebooter entry is normal. I think you've to reinstall once more. 

And did macOS threw any error while formatting SSD as APFS volume?

Fix to 

> I added the '-v' boot parameter and receive the following error:
**** ERROR: _LoginUIInitializeGraphics Can't install updated AppleEvent protocol.
**** ERROR: FDELoginUIInitializeUsers _LoginUIInitializeGraphics failed err: 1

https://olarila.com/forum/viewtopic.php?t=7050

**Comment by nojohnso** [comment]
I did a reinstall and it works now. I didn't use the FileVault feature this time. Thanks again for the guide.

Now to get my EDIMAX EW-7722UTn V2 working.

**Comment by verfasor** [comment]
Is your WiFi adapter based on Realtek? Check the driver I mentioned in the readme.md. It’ll work for Realtek adapters.

**Comment by nojohnso** [comment]
Yup. Mine is on the list from that repo as well. Does it matter if the device has current official drivers? I also tried the official drivers but they're not supported under Catalina.

**Comment by verfasor** [comment]
It doesn't matter. Just don't install multiple drivers. 

> I also tried the official drivers but they're not supported under Catalina.

A lot of vendors haven't added support for Catalina yet, it's a common issue. 

https://github.com/chris1111/Wireless-USB-Adapter-Clover

This is safe to use. Install the [latest package](https://github.com/chris1111/Wireless-USB-Adapter-Clover/releases/) and restart. Your WiFi adapter will work out of the box.

**Comment by nojohnso** [comment]
Fresh install, made sure my clover configs were set as specified, restarted, no WiFI still. Is there a way to see if macOS recognizes it's plugged in? It's not in my settings whatsoever.

**Comment by verfasor** [comment]
> Is there a way to see if macOS recognizes it's plugged in? 

About -> System Report -> USB. Check the status there.

**Comment by nojohnso** [comment]
Solution is to use V9 of the Wireless USB Adapter driver.
