### ISSUE TITLE
 usb wifi driver

### ISSUE THREAD

**Issue by ledungcobra** [mighildotcom/X230-Hackintosh#3]
What is the model of your nano-wifi adapter if it is comfast model please give me link to download kext for it. I can't find it work for my catalina mac os

**Comment by verfasor** [comment]
I don't use a nano adapter anymore. I use Atheros AR5B95, Lenovo part number 20002357 is a macOS supported/Lenovo-whitelisted card available for X230.

That being said, I've used Comfast CF-811 AC in the past. And for Catalina, you select the [latest driver package from here](https://github.com/chris1111/Wireless-USB-Adapter-Clover). It's unofficial but works. **[Click here](https://github.com/chris1111/Wireless-USB-Adapter-Clover/files/4301774/Wireless.USB.Adapter.Clover-V14.zip) to download the latest package.**
