### ISSUE TITLE
Turbo boost does not work after upgrading to 10.15.4

### ISSUE THREAD

**Issue by xiazuojie** [mighildotcom/X230-Hackintosh#4]
Max CPU frequency stays at 2.5GHz (base clock for 3120M) after upgrading to 10.15.4.
It used to boost to 3.1GHz (expected boost clock) with 10.15.2.

**Comment by xiazuojie** [comment]
Never mind. It works after generating my own SSDT.aml, following [here](https://www.tonymacx86.com/threads/quick-guide-to-generate-a-ssdt-for-cpu-power-management.177456/)

**Comment by verfasor** [comment]
Glad to hear 👍🏼. I haven’t tested the EFI against 10.15.4 also.
